---
title: "results"
output: md_document
---

```{r setup, echo=FALSE, warning=TRUE}
mmy:::warn_debug_makevars_flags()
require(mmy, quietly = TRUE)
```

Generate an example data.frame:
```{r}
n <- 1e5
df <- data.frame(
    Date = sort(sample(seq(as.Date("2019-02-27"), as.Date("2019-03-01"), by = "day"), n, replace = TRUE)),
    Category = sample(LETTERS[seq(4L)], n, replace = TRUE),
    Item = replicate(n, paste(sample(c(letters, LETTERS), 4L), collapse = "")),
    Stock = sample(1:100, n, replace = TRUE),
    Sold = sample(c(TRUE, FALSE), n, replace = TRUE)
  )
```

Display the structure of this object:
```{r}
str(df)
```

## ht

```{r}
system.time(mmy::ht(df, 5))
```

---

## search_list_names

```{r}
basic <- read_test_data("basic.RDS") # TODO read big list
microbenchmark::microbenchmark(
  c_recur = cat({nms <- names(c(basic, recursive = TRUE));nms[grep("color", nms)]}, sep = "\n",
  sapply = "TODO",
  search_list_names = mmy::search_list_names(basic, "color"),
  times = 1e4
)
```


---

File last created on *`r Sys.Date()`*
