#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP _ht_df(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_ht_df", (DL_FUNC) &_ht_df, 2},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_mmy(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
